[TTTE-14] Get practice history by test id and user id API & [TTTE-46] Submit answer by question id API
vtronghieu/toeic-exam-app pull request #24
Opened 2023-08-08 10:01 UTC by vtronghieu

2023-08-10 04:00 UTC, NguyenDinhBuiDuy requested changes

2023-08-14 08:21 UTC, minhtrungs013 commented on src/main/java/com/tip/dg4/toeic_exam/dto/PartTestDto.java
> +    private int totalQuestion;
I fix it

2023-08-14 08:21 UTC, minhtrungs013 commented on src/main/java/com/tip/dg4/toeic_exam/models/TestHistoryStatus.java
> +        return null;
I fix it

2023-08-14 08:21 UTC, minhtrungs013 commented on src/main/java/com/tip/dg4/toeic_exam/services/implement/PartTestServiceImpl.java
> +                int lastIndex = testHistories.size() - 1;
I fix it

2023-08-14 08:21 UTC, minhtrungs013 commented on src/main/java/com/tip/dg4/toeic_exam/mappers/UserAnswerMapper.java
> +//        ListenAnswerDto listenAnswerDto = listenAnswerMapper.convertModelToDto(userAnswer.getListenAnswer());
I fix it

2023-08-14 08:23 UTC, merged